INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("foo", "MISC", 100, 20190411, 20190701);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("Math WHIZ", "game", 5000, 20190311, 20190621);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("Coding school", "education", 10000, 20190314, 20190530);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("MADE", "charity", 10000, 20180402, 20190402);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("Coolermax", "invention", 45000, 20190304, 20190704);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("Codex", "game", 100000, 20180501, 20200106);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("Star-school", "education", 40000, 20180522, 20200711);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("barcraft", "MISC", 100, 20170204, 20190722);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("Mymethlab", "game", 5000, 20180611, 20190922);
INSERT INTO projects (title, category, funding_goal,  start_date, end_date ) VALUES ("Math Tycoon", "education", 1000, 20190221, 20201130);
INSERT INTO users (name, age ) VALUES ("Brian", 21);
INSERT INTO users (name, age ) VALUES ("Joe", 30);
INSERT INTO users (name, age ) VALUES ("Susan ", 22);
INSERT INTO users (name, age ) VALUES ("Ashley", 51);
INSERT INTO users (name, age ) VALUES ("Maria" , 56);
INSERT INTO users (name, age ) VALUES ("Emma", 55);
INSERT INTO users (name, age ) VALUES ("Brian", 52);
INSERT INTO users (name, age ) VALUES ("Marley", 31);
INSERT INTO users (name, age ) VALUES ("Dylan", 42);
INSERT INTO users (name, age ) VALUES  ("Marcus", 66);
INSERT INTO users (name, age ) VALUES ("foo", 77);
INSERT INTO users (name, age ) VALUES ("barfoo", 52);
INSERT INTO users (name, age ) VALUES ("quex", 115);
INSERT INTO users (name, age ) VALUES ("cuberoot",41);
INSERT INTO users (name, age ) VALUES ("questsa", 77);
INSERT INTO users (name, age ) VALUES ("ssoa", 41);
INSERT INTO users (name, age ) VALUES ("saha", 51);
INSERT INTO users (name, age ) VALUES ("faja", 25);
INSERT INTO users (name, age ) VALUES ("tara", 22);
INSERT INTO users (name, age ) VALUES ("sga", 71);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (1100, 3, 5);
INSERT INTO pledges (amount, user_id, project_id ) VALUES  (30, 1, 9);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (44, 3, 5);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (500, 3, 8);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (40, 4, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (100, 9, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (11, 4, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (151, 8, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (51, 9, 10);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (100, 15, 5);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (15, 12, 3);
INSERT INTO pledges (amount, user_id, project_id ) VALUES ( 100, 20, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (105, 18, 10);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (100, 12, 7);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (50, 15, 3);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (100, 11, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (5, 16, 2);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (5, 11, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (1, 1,1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (2, 2 , 2);
INSERT INTO pledges (amount, user_id, project_id ) VALUES ( 2, 11, 3);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (5, 13, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (10, 6, 3);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (10, 6, 4);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (4, 6, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (4, 11, 5);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (100, 11, 8 );
INSERT INTO pledges (amount, user_id, project_id ) VALUES  (40, 3, 5);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (50, 2, 2);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (55, 5, 2);